name: Deploy CMS

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: imagina/basequasar-app
          token: ${{ secrets.DEPLOY_ADMIN_THEME }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: setup quasar & dependencies
        run: |
          echo "Install Quasar CLI"
          npm install -g @quasar/cli
          echo "Install Yarn"
          npm install --global yarn
          echo "Install node Dependencies"
          yarn install

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Github Credentials
        run: |
          git config --global user.name "Imagina Actions Bot"
          git config --global user.email "carlosdevia@imaginacolombia.com"
          git config --global url."https://${{ secrets.DEPLOY_ADMIN_THEME }}@github.com/".insteadOf "https://github.com/"

      - name: Set Branch to push deploy
        id: set_branch
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "current_branch=$branch" >> "$GITHUB_ENV"
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "branch_deploy=v10.x" >> "$GITHUB_ENV"
          else
            # Set branch_deploy to the current branch name
            echo "branch_deploy=$branch" >> "$GITHUB_ENV"
          fi

      - name: Prepare Staging to Release
        run: |
          git fetch --unshallow
          git checkout $current_branch
          git submodule foreach --recursive '
            git fetch --all
            git checkout $current_branch || git checkout -b $current_branch origin/$current_branch
          '

      - name: Build as PWA
        run: quasar build -m pwa

      - name: Deploy CMS
        run: |
          if [ "$branch_deploy" = "v12.x" ]; then
            echo "🚀 Deploying to imagina/imaginacms-icms (dist folder)"
            git clone https://github.com/imagina/imaginacms-icms.git tmp_repo
            cd tmp_repo
            git checkout $branch_deploy
            rm -rf dist
            cp -r ../dist/pwa ./dist
            git add .
            git commit -m "+Release: ICMS dist update"
            git push origin $branch_deploy
          else
            echo "🚀 Deploying to imagina/imaginacmsadmin-theme (iadmin folder)"
            git clone https://github.com/imagina/imaginacmsadmin-theme.git tmp_repo
            cd tmp_repo
            git checkout $branch_deploy
            rm -rf iadmin
            cp -r ../dist/pwa ./iadmin
            git add .
            git commit -m "+Release: Iadmin"
            git push origin $branch_deploy
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ADMIN_THEME }}
