name: Deploy

on:
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'Target Branch to release'
        required: true
        default: 'staging'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Quasar CLI
        run: npm install -g @quasar/cli
          
      - name: Install dependencies
        run: npm install

      - name: Remove @imagina folder
        run: rm -rf node_modules/@imagina

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Change to branch Staging
        run: |
          git submodule foreach --recursive git checkout staging
          git checkout -b staging

      - name: Build
        run: quasar build -m pwa

      - name: Rename folder PWA to IADMIN
        run: mv dist/pwa iadmin

      - name: Publish iadmin folder in main repositorie
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'iadmin'
          destination_repo: 'imagina/imaginacmsadmin-theme'
          destination_branch: 'CD/CI'
          destination_folder: './'
          user_email: 'jose.alejandro.sabogal.loiaza@gmail.com'
          user_name: 'AlejandroDev99'
          commit_message: 'Implementing CD'